# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_targetList = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_targetList.setGeometry(QtCore.QRect(10, 10, 251, 121))
        self.groupBox_targetList.setObjectName("groupBox_targetList")
        self.listWidget_ips = QtWidgets.QListWidget(self.groupBox_targetList)
        self.listWidget_ips.setGeometry(QtCore.QRect(10, 20, 201, 91))
        self.listWidget_ips.setObjectName("listWidget_ips")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ips.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ips.addItem(item)
        self.pushButton_addip = QtWidgets.QPushButton(self.groupBox_targetList)
        self.pushButton_addip.setGeometry(QtCore.QRect(220, 20, 21, 23))
        self.pushButton_addip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_addip.setObjectName("pushButton_addip")
        self.pushButton_delip = QtWidgets.QPushButton(self.groupBox_targetList)
        self.pushButton_delip.setGeometry(QtCore.QRect(220, 50, 21, 23))
        self.pushButton_delip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_delip.setObjectName("pushButton_delip")
        self.pushButton_cleanip = QtWidgets.QPushButton(self.groupBox_targetList)
        self.pushButton_cleanip.setGeometry(QtCore.QRect(220, 80, 21, 23))
        self.pushButton_cleanip.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_cleanip.setObjectName("pushButton_cleanip")
        self.groupBox_portList = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_portList.setGeometry(QtCore.QRect(280, 10, 251, 121))
        self.groupBox_portList.setObjectName("groupBox_portList")
        self.listWidget_ports = QtWidgets.QListWidget(self.groupBox_portList)
        self.listWidget_ports.setGeometry(QtCore.QRect(10, 20, 201, 91))
        self.listWidget_ports.setObjectName("listWidget_ports")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ports.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ports.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ports.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ports.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ports.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ports.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_ports.addItem(item)
        self.pushButton_addport = QtWidgets.QPushButton(self.groupBox_portList)
        self.pushButton_addport.setGeometry(QtCore.QRect(220, 20, 21, 23))
        self.pushButton_addport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_addport.setObjectName("pushButton_addport")
        self.pushButton_delport = QtWidgets.QPushButton(self.groupBox_portList)
        self.pushButton_delport.setGeometry(QtCore.QRect(220, 50, 21, 23))
        self.pushButton_delport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_delport.setObjectName("pushButton_delport")
        self.pushButton_cleanport = QtWidgets.QPushButton(self.groupBox_portList)
        self.pushButton_cleanport.setGeometry(QtCore.QRect(220, 80, 21, 23))
        self.pushButton_cleanport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_cleanport.setObjectName("pushButton_cleanport")
        self.pushButton_scan = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_scan.setGeometry(QtCore.QRect(710, 50, 61, 41))
        self.pushButton_scan.setObjectName("pushButton_scan")
        self.groupBox_result = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_result.setGeometry(QtCore.QRect(10, 140, 781, 411))
        self.groupBox_result.setObjectName("groupBox_result")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_result)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 761, 381))
        self.tableWidget.setMaximumSize(QtCore.QSize(761, 16777215))
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.groupBox_settings = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_settings.setGeometry(QtCore.QRect(550, 20, 151, 111))
        self.groupBox_settings.setObjectName("groupBox_settings")
        self.label = QtWidgets.QLabel(self.groupBox_settings)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label.setLineWidth(1)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_settings)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 41, 21))
        self.label_2.setLineWidth(1)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_settings)
        self.comboBox.setGeometry(QtCore.QRect(50, 60, 71, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox_settings)
        self.label_3.setGeometry(QtCore.QRect(120, 20, 41, 21))
        self.label_3.setLineWidth(1)
        self.label_3.setObjectName("label_3")
        self.comboBox_speed = QtWidgets.QComboBox(self.groupBox_settings)
        self.comboBox_speed.setGeometry(QtCore.QRect(50, 20, 71, 22))
        self.comboBox_speed.setEditable(True)
        self.comboBox_speed.setObjectName("comboBox_speed")
        self.comboBox_speed.addItem("")
        self.comboBox_speed.addItem("")
        self.comboBox_speed.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_targetList.setTitle(_translate("MainWindow", "TargetList"))
        __sortingEnabled = self.listWidget_ips.isSortingEnabled()
        self.listWidget_ips.setSortingEnabled(False)
        item = self.listWidget_ips.item(0)
        item.setText(_translate("MainWindow", "localhost"))
        item = self.listWidget_ips.item(1)
        item.setText(_translate("MainWindow", "192.168.0.1/24"))
        self.listWidget_ips.setSortingEnabled(__sortingEnabled)
        self.pushButton_addip.setText(_translate("MainWindow", "+"))
        self.pushButton_delip.setText(_translate("MainWindow", "-"))
        self.pushButton_cleanip.setText(_translate("MainWindow", "X"))
        self.groupBox_portList.setTitle(_translate("MainWindow", "PortList"))
        __sortingEnabled = self.listWidget_ports.isSortingEnabled()
        self.listWidget_ports.setSortingEnabled(False)
        item = self.listWidget_ports.item(0)
        item.setText(_translate("MainWindow", "80"))
        item = self.listWidget_ports.item(1)
        item.setText(_translate("MainWindow", "21"))
        item = self.listWidget_ports.item(2)
        item.setText(_translate("MainWindow", "22"))
        item = self.listWidget_ports.item(3)
        item.setText(_translate("MainWindow", "53"))
        item = self.listWidget_ports.item(4)
        item.setText(_translate("MainWindow", "8080"))
        item = self.listWidget_ports.item(5)
        item.setText(_translate("MainWindow", "8000"))
        item = self.listWidget_ports.item(6)
        item.setText(_translate("MainWindow", "8090"))
        self.listWidget_ports.setSortingEnabled(__sortingEnabled)
        self.pushButton_addport.setText(_translate("MainWindow", "+"))
        self.pushButton_delport.setText(_translate("MainWindow", "-"))
        self.pushButton_cleanport.setText(_translate("MainWindow", "X"))
        self.pushButton_scan.setText(_translate("MainWindow", "Scan"))
        self.groupBox_result.setTitle(_translate("MainWindow", "Result"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Service"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Banner"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "localhost:8080"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Apache2.7"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_settings.setTitle(_translate("MainWindow", "Settings"))
        self.label.setText(_translate("MainWindow", "Speed: "))
        self.label_2.setText(_translate("MainWindow", "Type: "))
        self.comboBox.setItemText(0, _translate("MainWindow", "synScan"))
        self.comboBox.setItemText(1, _translate("MainWindow", "tcpScan"))
        self.comboBox.setItemText(2, _translate("MainWindow", "udpScan"))
        self.label_3.setText(_translate("MainWindow", "kbps"))
        self.comboBox_speed.setCurrentText(_translate("MainWindow", "synScan"))
        self.comboBox_speed.setItemText(0, _translate("MainWindow", "synScan"))
        self.comboBox_speed.setItemText(1, _translate("MainWindow", "tcpScan"))
        self.comboBox_speed.setItemText(2, _translate("MainWindow", "udpScan"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

